language: node_js
addons:
  firefox: "48.0"
node_js:
  - "6"
sudo: false
before_install: npm install -g gulp
install: npm install
before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    -  sleep 6
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
